//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::ScenarioFormat;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "scenario")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub scenario_format: ScenarioFormat,
    pub title: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::plan::Entity")]
    Plan,
    #[sea_orm(has_many = "super::scenario_file::Entity")]
    ScenarioFile,
}

impl Related<super::plan::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plan.def()
    }
}

impl Related<super::scenario_file::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScenarioFile.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
