//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "executor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub slurm_job_id: i32,
    pub slurm_array_id: i32,
    pub slurm_node_list: String,
    pub hostname: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::task_run::Entity")]
    TaskRun,
}

impl Related<super::task_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskRun.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
