//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub plan_id: i32,
    pub av_id: i32,
    pub worker_id: i32,
    #[sea_orm(column_type = "custom(\"enum_text\")", nullable)]
    pub status: Option<String>,
    pub created_at: DateTimeUtc,
    pub executed_at: Option<DateTimeUtc>,
    pub finished_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::av::Entity",
        from = "Column::AvId",
        to = "super::av::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Av,
    #[sea_orm(
        belongs_to = "super::plan::Entity",
        from = "Column::PlanId",
        to = "super::plan::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Plan,
    #[sea_orm(
        belongs_to = "super::worker::Entity",
        from = "Column::WorkerId",
        to = "super::worker::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Worker,
}

impl Related<super::av::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Av.def()
    }
}

impl Related<super::plan::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plan.def()
    }
}

impl Related<super::worker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Worker.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
