//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use super::sea_orm_active_enums::TaskStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "task")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub plan_id: i32,
    pub av_id: i32,
    pub worker_id: Option<i32>,
    pub status: TaskStatus,
    pub created_at: DateTime,
    pub executed_at: Option<DateTime>,
    pub finished_at: Option<DateTime>,
    pub simulator_id: i32,
    pub sampler_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::av::Entity",
        from = "Column::AvId",
        to = "super::av::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Av,
    #[sea_orm(
        belongs_to = "super::plan::Entity",
        from = "Column::PlanId",
        to = "super::plan::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Plan,
    #[sea_orm(
        belongs_to = "super::sampler::Entity",
        from = "Column::SamplerId",
        to = "super::sampler::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Sampler,
    #[sea_orm(
        belongs_to = "super::simulator::Entity",
        from = "Column::SimulatorId",
        to = "super::simulator::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Simulator,
    #[sea_orm(
        belongs_to = "super::worker::Entity",
        from = "Column::WorkerId",
        to = "super::worker::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Worker,
}

impl Related<super::av::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Av.def()
    }
}

impl Related<super::plan::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plan.def()
    }
}

impl Related<super::sampler::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sampler.def()
    }
}

impl Related<super::simulator::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Simulator.def()
    }
}

impl Related<super::worker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Worker.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
